@startuml
'https://plantuml.com/class-diagram

abstract class AbstractClass {
    TemplateMethod()
    PrimitiveOperation1()
    PrimitiveOperation2()
}
note right of AbstractClass::TemplateMethod
  ...
  PrimitiveOperation1()
  ...
  PrimitiveOperation2
  ...
end note

class ConcreteClass extends AbstractClass {
    PrimitiveOperation1()
    PrimitiveOperation2()
}

@enduml