@startuml
'https://plantuml.com/class-diagram

class RemoteControl {
    + on () : void
    + off () : void
    + setChannel () : void
    ..
    // more methods
}

class RCAControl {
    + on () : void
    + off () : void
    + setChannel () : void
    ..
    // more methods
}
note left of RCAControl::setChannel
  {
    tuneChannel(channel);
  }
end note

class SonyControl {
    + on () : void
    + off () : void
    + setChannel () : void
    ..
    // more methods
}


RemoteControl <|-- SonyControl
RemoteControl <|-- RCAControl

@enduml